document.addEventListener("DOMContentLoaded", () => {
  const apiBase = (document.querySelector('meta[name="public-api-base-url"]')?.content || "").replace(/\/$/, "");
  const pages = [...document.querySelectorAll("[data-page]")];
  const state = { eventId: "", sectionId: "", orderNumber: "", orderAccessToken: "", sectionName: "", ticketPrice: 0, ticketQuantity: 1, currency: "USD", paymentMethod: "paypal" };
  const api = async (path, options = {}, guest = false) => {
    const headers = { "Content-Type": "application/json", ...(options.headers || {}) };
    if (guest && state.orderAccessToken) headers["X-Order-Access-Token"] = state.orderAccessToken;
    const response = await fetch(`${apiBase}/api/v1${path}`, { credentials: "include", ...options, headers });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(payload.error?.message || "Request failed. Please try again.");
    return payload.data;
  };
  const toastRegion = document.getElementById("toast-region");
  const showToast = (message, type = "info") => { if (!toastRegion) return; const item = document.createElement("div"); item.className = `toast toast-${type}`; item.textContent = message; item.setAttribute("role", type === "error" ? "alert" : "status"); toastRegion.append(item); setTimeout(() => item.remove(), 4000); };
  const route = (name) => { pages.forEach((page) => { const active = page.dataset.page === name; page.hidden = !active; page.classList.toggle("is-active", active); }); document.querySelectorAll("[data-route]").forEach((control) => control.classList.toggle("is-active", control.dataset.route === name)); if (window.location.hash !== `#${name}`) history.pushState({}, "", `#${name}`); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const displayMoney = (minor, currency) => { try { return new Intl.NumberFormat(undefined, { style: "currency", currency }).format(Number(minor || 0) / 100); } catch { return `${currency} ${Number(minor || 0) / 100}`; } };
  const removeAccountAndMembershipUi = () => { ["account", "membership"].forEach((name) => document.querySelectorAll(`[data-route="${name}"], [href="#${name}"], [data-page="${name}"]`).forEach((node) => node.remove())); document.querySelectorAll("[data-membership-cta], #account-actions").forEach((node) => node.remove()); const successAccount = document.querySelector('#page-success [data-route="account"]'); if (successAccount) { successAccount.dataset.route = "events"; successAccount.textContent = "Browse more events"; } };
  const renderEvents = (events) => { const list = document.getElementById("event-list"); if (!list) return; list.replaceChildren(); const count = document.getElementById("event-count"); if (count) count.textContent = String(events.length); if (!events.length) return list.append(Object.assign(document.createElement("p"), { className: "panel-description", textContent: "No published events are currently available." })); events.forEach((event) => { const item = document.createElement("article"); item.className = "event-row"; const starts = new Date(event.starts_at); item.innerHTML = `<div class="date-block"><span>${starts.toLocaleString(undefined, { month: "short" }).toUpperCase()}</span><strong>${String(starts.getDate()).padStart(2, "0")}</strong><small>${starts.toLocaleString(undefined, { weekday: "short" }).toUpperCase()}</small></div><div class="event-row-main"><p class="event-type">Live event</p><h3>${event.title}</h3><p>${starts.toLocaleString()} • ${event.venue}, ${event.city}</p></div><div class="event-row-price"><span>From</span><strong>${displayMoney(event.starting_price_minor, event.currency)}</strong></div>`; const button = document.createElement("button"); button.className = "button button-primary button-small"; button.type = "button"; button.textContent = "View options"; button.addEventListener("click", () => loadEvent(event.slug)); item.append(button); list.append(item); }); };
  const loadEvents = async (query = "", filters = {}) => { const params = new URLSearchParams(); if (query) params.set("q", query); if (filters.city) params.set("city", filters.city); if (filters.from) params.set("from", filters.from); if (filters.to) params.set("to", filters.to); try { renderEvents(await api(`/events${params.size ? `?${params}` : ""}`)); } catch (error) { showToast(error.message, "error"); } };
  const loadEvent = async (slug) => { try { const event = await api(`/events/${encodeURIComponent(slug)}`); state.eventId = event.id; state.currency = event.currency; const title = document.getElementById("event-details-title"); if (title) title.textContent = event.title; const list = document.querySelector(".ticket-option-list"); if (list) { list.replaceChildren(); event.sections.forEach((section, index) => { const label = document.createElement("label"); label.className = `ticket-option${index === 0 ? " is-selected" : ""}`; label.innerHTML = `<input type="radio" name="ticket-option" value="${section.id}"><span class="ticket-option-main"><span class="ticket-option-heading"><strong>${section.name}</strong></span><span class="ticket-benefits">${section.description || "Order request section"}</span><span class="scarcity">${section.available_quantity} currently available</span></span><span class="ticket-option-price"><small>Each</small><strong>${displayMoney(section.price_minor, event.currency)}</strong></span>`; const input = label.querySelector("input"); input.checked = index === 0; input.addEventListener("change", () => { state.sectionId = section.id; state.sectionName = section.name; state.ticketPrice = Number(section.price_minor) / 100; updateSummary(); }); list.append(label); if (index === 0) { state.sectionId = section.id; state.sectionName = section.name; state.ticketPrice = Number(section.price_minor) / 100; } }); } updateSummary(); route("event-details"); } catch (error) { showToast(error.message, "error"); } };
  const updateSummary = () => { const total = state.ticketPrice * state.ticketQuantity; const values = { "summary-section": state.sectionName, "summary-quantity": `${state.ticketQuantity} ${state.ticketQuantity === 1 ? "ticket" : "tickets"}`, "summary-subtotal": displayMoney(total * 100, state.currency), "summary-total": displayMoney(total * 100, state.currency) }; Object.entries(values).forEach(([id, value]) => { const node = document.getElementById(id); if (node) node.textContent = value; }); };
  const attachGuestStatus = () => {
    const actions = document.querySelector("#page-success .success-actions");
    if (!actions || actions.querySelector("[data-guest-status]")) return;
    const button = document.createElement("button");
    button.className = "button button-outline";
    button.type = "button";
    button.textContent = "Check order status";
    button.dataset.guestStatus = "true";
    button.addEventListener("click", async () => {
      try {
        const order = await api(`/orders/${encodeURIComponent(state.orderNumber)}`, {}, true);
        showToast(`${order.reference}: ${String(order.current_payment_status || order.payment_status).replaceAll("_", " ")}`);
        if (order.current_payment_status === "payment_details_ready") {
          const details = await api(`/orders/${encodeURIComponent(state.orderNumber)}/payments/${order.payment_id}/instructions`, {}, true);
          showToast(`Payment reference: ${details.payment_reference || "available in your order"}`);
        }
      } catch (error) { showToast(error.message, "error"); }
    });
    actions.append(button);
  };
  document.querySelectorAll("[data-route]").forEach((control) => control.addEventListener("click", (event) => { const name = control.dataset.route; if (!pages.some((page) => page.dataset.page === name)) return; event.preventDefault(); route(name); }));
  document.querySelectorAll('input[name="ticket-quantity"]').forEach((input) => input.addEventListener("change", () => { state.ticketQuantity = Number(input.value) || 1; updateSummary(); }));
  document.querySelectorAll('input[name="payment-method"]').forEach((input) => input.addEventListener("change", () => { state.paymentMethod = input.value.replace("-", "_"); document.querySelectorAll("[data-payment-panel]").forEach((panel) => { panel.hidden = panel.dataset.paymentPanel !== input.value; }); }));
  document.querySelector('select[name="phone-country"]')?.addEventListener("change", (event) => { document.querySelector("[data-other-country-field]")?.toggleAttribute("hidden", event.target.value !== "OTHER"); });
  document.getElementById("checkout-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity() || !state.eventId || !state.sectionId) return; const data = new FormData(form); const button = form.querySelector('button[type="submit"]'); button.disabled = true; try { const result = await api("/orders", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ eventId: state.eventId, sectionId: state.sectionId, quantity: state.ticketQuantity, paymentMethod: state.paymentMethod, contactName: `${data.get("first-name")} ${data.get("last-name")}`.trim(), contactEmail: data.get("email"), contactPhone: data.get("phone"), contactCountry: data.get("phone-country") === "OTHER" ? data.get("phone-country-name") : data.get("phone-country") }) }); state.orderNumber = result.reference; state.orderAccessToken = result.accessToken; sessionStorage.setItem("guest-order", JSON.stringify({ reference: result.reference, accessToken: result.accessToken })); const orderNumber = document.getElementById("order-number"); if (orderNumber) orderNumber.textContent = result.reference; const status = document.getElementById("payment-status-message"); if (status) status.textContent = result.message; route("success"); } catch (error) { showToast(error.message, "error"); } finally { button.disabled = false; } });
  const serviceForm = document.getElementById("service-form"); serviceForm?.addEventListener("submit", async (event) => { event.preventDefault(); if (!serviceForm.reportValidity()) return; const data = new FormData(serviceForm); try { await api("/service-requests", { method: "POST", body: JSON.stringify({ category: "general", fullName: data.get("service-name"), email: data.get("service-email"), phone: data.get("service-phone"), message: data.get("service-message") }) }); serviceForm.reset(); showToast("Your enquiry has been received.", "success"); } catch (error) { showToast(error.message, "error"); } });
  const supportForm = document.getElementById("support-form"); supportForm?.addEventListener("submit", async (event) => { event.preventDefault(); if (!supportForm.reportValidity()) return; const data = new FormData(supportForm); try { await api("/support-requests", { method: "POST", body: JSON.stringify({ name: data.get("support-name"), email: data.get("support-email"), orderReference: data.get("order-number"), message: data.get("support-message") }) }); supportForm.reset(); showToast("Your support request has been received.", "success"); } catch (error) { showToast(error.message, "error"); } });
  removeAccountAndMembershipUi(); try { const saved = JSON.parse(sessionStorage.getItem("guest-order") || "null"); if (saved) { state.orderNumber = saved.reference; state.orderAccessToken = saved.accessToken; } } catch {} attachGuestStatus(); updateSummary(); loadEvents(); route(window.location.hash.replace(/^#/, "") || "home");
});
