begin;
create extension if not exists pgcrypto;
create function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create table profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null check(length(full_name) between 2 and 120),phone text,country char(2),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'Customer')); return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_auth_user();
create table admin_roles(id uuid primary key default gen_random_uuid(),name text not null unique check(name in ('Super Administrator','Event Manager','Finance Manager','Membership Manager')),description text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table admin_permissions(id uuid primary key default gen_random_uuid(),code text not null unique,description text not null,created_at timestamptz not null default now());
create table admin_role_permissions(role_id uuid not null references admin_roles(id) on delete cascade,permission_id uuid not null references admin_permissions(id) on delete cascade,primary key(role_id,permission_id));
create table admin_users(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references profiles(id),role_id uuid not null references admin_roles(id),is_super_admin boolean not null default false,status text not null default 'active' check(status in ('invited','active','disabled')),two_factor_required boolean not null default true,last_login_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create unique index one_super_admin on admin_users(is_super_admin) where is_super_admin=true and deleted_at is null;
create table admin_login_attempts(id uuid primary key default gen_random_uuid(),email_hash text not null,succeeded boolean not null,ip_address inet,user_agent text,created_at timestamptz not null default now());
create index admin_login_attempts_created_idx on admin_login_attempts(created_at desc);

create table events(id uuid primary key default gen_random_uuid(),slug text not null unique,title text not null,description text not null default '',venue text not null,city text not null,country char(2) not null,starts_at timestamptz not null,currency char(3) not null,status text not null default 'draft' check(status in ('draft','published','unpublished','archived')),created_by uuid references admin_users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create index events_public_idx on events(status,starts_at) where deleted_at is null;
create table event_sections(id uuid primary key default gen_random_uuid(),event_id uuid not null references events(id),name text not null,description text not null default '',price_minor bigint not null check(price_minor>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,unique(event_id,name));
create index event_sections_event_idx on event_sections(event_id) where deleted_at is null;
create table ticket_inventory(id uuid primary key default gen_random_uuid(),section_id uuid not null unique references event_sections(id),available_quantity integer not null check(available_quantity>=0),held_quantity integer not null default 0 check(held_quantity>=0),sold_quantity integer not null default 0 check(sold_quantity>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(held_quantity+sold_quantity<=available_quantity));

create table orders(id uuid primary key default gen_random_uuid(),profile_id uuid references profiles(id),event_id uuid not null references events(id),reference text not null unique,status text not null check(status in ('pending_payment','payment_under_review','payment_successful','payment_failed','cancelled')),payment_status text not null check(payment_status in ('pending','verification_required','successful','failed','cancelled','refunded','partially_refunded')),currency char(3) not null,subtotal_minor bigint not null check(subtotal_minor>0),total_minor bigint not null check(total_minor>0),contact_name text not null,contact_email text not null,checkout_idempotency_key text not null unique,hold_expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index orders_profile_idx on orders(profile_id,created_at desc);create index orders_status_idx on orders(status,created_at desc);create index orders_event_idx on orders(event_id);
create table order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id),event_section_id uuid not null references event_sections(id),description text not null,quantity integer not null check(quantity>0),unit_price_minor bigint not null check(unit_price_minor>0),total_minor bigint not null check(total_minor=quantity*unit_price_minor),created_at timestamptz not null default now());
create index order_items_order_idx on order_items(order_id);
create table payments(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id),provider text not null check(provider in ('paypal','card_provider','manual')),method text not null check(method in ('paypal','card','cash_app','chime')),status text not null check(status in ('pending','verification_required','successful','failed','cancelled','refunded','partially_refunded')),amount_minor bigint not null check(amount_minor>0),currency char(3) not null,provider_reference text,idempotency_key text not null,verification_source text,verified_at timestamptz,verified_by uuid references admin_users(id),failure_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,idempotency_key));
create unique index payments_provider_ref_unique on payments(provider,provider_reference) where provider_reference is not null;create index payments_order_idx on payments(order_id);create index payments_review_idx on payments(status,method) where status in ('pending','verification_required');
create table manual_payment_submissions(id uuid primary key default gen_random_uuid(),payment_id uuid not null references payments(id),evidence_storage_path text,customer_note text,status text not null default 'submitted' check(status in ('submitted','under_review','accepted','rejected')),reviewed_by uuid references admin_users(id),review_reason text,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index manual_submissions_payment_idx on manual_payment_submissions(payment_id,created_at desc);
create table payment_webhook_events(id uuid primary key default gen_random_uuid(),provider text not null,event_id text not null,event_type text not null,payload jsonb not null,signature_verified boolean not null default false,processing_status text not null default 'received' check(processing_status in ('received','processed','ignored','rejected')),processing_error text,processed_at timestamptz,created_at timestamptz not null default now(),unique(provider,event_id));

create table membership_applications(id uuid primary key default gen_random_uuid(),profile_id uuid references profiles(id),full_name text not null,email text not null,country char(2) not null,reason text not null,interest text not null check(interest in ('exclusive_content','meet_and_greet','merchandise','general_membership')),status text not null check(status in ('pending','approved','declined','on_hold')),internal_notes text,reviewed_by uuid references admin_users(id),reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index active_membership_application_email on membership_applications(lower(email)) where status in ('pending','on_hold');create index membership_app_profile_idx on membership_applications(profile_id,created_at desc);
create table memberships(id uuid primary key default gen_random_uuid(),profile_id uuid references profiles(id),application_id uuid not null unique references membership_applications(id),status text not null check(status in ('active','expired','suspended','cancelled')),starts_at timestamptz not null,expires_at timestamptz not null check(expires_at>starts_at),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index memberships_profile_idx on memberships(profile_id,status);
create table service_requests(id uuid primary key default gen_random_uuid(),profile_id uuid references profiles(id),category text not null check(category in ('private_event','appearance','meet_and_greet','general')),full_name text not null,email text not null,phone text,message text not null,status text not null check(status in ('new','assigned','in_progress','waiting_customer','resolved','archived')),assigned_to uuid references admin_users(id),internal_notes text,reply_draft text,archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());create index service_requests_profile_idx on service_requests(profile_id,created_at desc);create index service_requests_queue_idx on service_requests(status,created_at);
create table customer_support_requests(id uuid primary key default gen_random_uuid(),profile_id uuid references profiles(id),name text not null,email text not null,order_reference text,message text not null,status text not null default 'new' check(status in ('new','received','closed')),ip_hash text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());create index support_requests_profile_idx on customer_support_requests(profile_id,created_at desc);
create table notifications(id uuid primary key default gen_random_uuid(),profile_id uuid references profiles(id),admin_user_id uuid references admin_users(id),kind text not null,title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now(),check((profile_id is null)<>(admin_user_id is null)));create index notifications_profile_idx on notifications(profile_id,created_at desc);create index notifications_admin_idx on notifications(admin_user_id,created_at desc);
create table audit_logs(id uuid primary key default gen_random_uuid(),admin_user_id uuid references admin_users(id),action text not null,entity_type text not null,entity_id uuid,request_id text,reason text,metadata jsonb not null default '{}',created_at timestamptz not null default now());create index audit_logs_entity_idx on audit_logs(entity_type,entity_id,created_at desc);create index audit_logs_admin_idx on audit_logs(admin_user_id,created_at desc);
create table app_settings(key text primary key,value jsonb not null default '{}',updated_by uuid references admin_users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table app_settings enable row level security;
create trigger app_settings_updated before update on app_settings for each row execute function public.set_updated_at();

do $$ declare t text; begin foreach t in array array['profiles','admin_roles','admin_users','events','event_sections','ticket_inventory','orders','payments','manual_payment_submissions','membership_applications','memberships','service_requests','customer_support_requests'] loop execute format('create trigger %I_updated before update on %I for each row execute function public.set_updated_at()',t,t); end loop; end $$;

alter table profiles enable row level security;alter table admin_roles enable row level security;alter table admin_permissions enable row level security;alter table admin_role_permissions enable row level security;alter table admin_users enable row level security;alter table admin_login_attempts enable row level security;alter table events enable row level security;alter table event_sections enable row level security;alter table ticket_inventory enable row level security;alter table orders enable row level security;alter table order_items enable row level security;alter table payments enable row level security;alter table manual_payment_submissions enable row level security;alter table payment_webhook_events enable row level security;alter table membership_applications enable row level security;alter table memberships enable row level security;alter table service_requests enable row level security;alter table customer_support_requests enable row level security;alter table notifications enable row level security;alter table audit_logs enable row level security;
create policy own_profile on profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy own_orders on orders for select using(profile_id=auth.uid());
create policy own_order_items on order_items for select using(exists(select 1 from orders o where o.id=order_id and o.profile_id=auth.uid()));
create policy own_payments on payments for select using(exists(select 1 from orders o where o.id=order_id and o.profile_id=auth.uid()));
create policy own_membership_apps on membership_applications for select using(profile_id=auth.uid());
create policy own_memberships on memberships for select using(profile_id=auth.uid());
create policy own_services on service_requests for select using(profile_id=auth.uid());
create policy own_support on customer_support_requests for select using(profile_id=auth.uid());
create policy own_notifications on notifications for select using(profile_id=auth.uid());

create function public.protect_super_admin() returns trigger language plpgsql as $$ begin if old.is_super_admin and (tg_op='DELETE' or new.is_super_admin=false or new.role_id<>old.role_id or new.status<>'active' or new.deleted_at is not null) then raise exception 'Super Administrator is protected'; end if; return case when tg_op='DELETE' then old else new end; end $$;
create trigger protect_super_admin before update or delete on admin_users for each row execute function public.protect_super_admin();
create function public.release_expired_order_holds() returns integer language plpgsql security definer set search_path=public as $$ declare released integer; begin with expired as (select o.id,oi.event_section_id,oi.quantity from orders o join order_items oi on oi.order_id=o.id where o.status='pending_payment' and o.hold_expires_at<now() for update of o), adjusted as (update ticket_inventory ti set held_quantity=greatest(0,ti.held_quantity-e.quantity),updated_at=now() from expired e where ti.section_id=e.event_section_id returning e.id) update orders set status='cancelled',payment_status='cancelled',updated_at=now() where id in(select id from adjusted); get diagnostics released=row_count; return released; end $$;
create function public.expire_memberships() returns integer language plpgsql security definer set search_path=public as $$ declare changed integer; begin update memberships set status='expired',updated_at=now() where status='active' and expires_at<=now();get diagnostics changed=row_count;return changed;end $$;
revoke all on function public.release_expired_order_holds() from public,anon,authenticated;
revoke all on function public.expire_memberships() from public,anon,authenticated;
commit;
